<?php

declare(strict_types=1);

namespace App\Events;

use App\Domain\Audit\Data\AuditEntryData;
use App\Enums\AuditAction;
use App\Models\Booking;
use App\Models\Departure;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Events\Dispatchable;

/**
 * Somebody asked for a list with passport numbers on it
 * (spec OPS-10, GDR-6, SEC-16).
 *
 * ## Why this row exists at all
 *
 * GDR-6 says document numbers appear in the manifest export **and nowhere
 * else** — not in serialisation, not in logs, not in Sentry, not in a webhook,
 * not in the ordinary CSVs. That is a strong claim, and this row is what makes
 * it checkable: if the numbers left the building, they left through here, and
 * here says who and when.
 *
 * ## Fired on inclusion, not on generation
 *
 * A crew list of names and nationalities is an ordinary export. Logging every
 * one of those would fill the trail with rows nobody needs to read, which is how
 * a trail stops being read at all — so the row is written only when the manifest
 * actually carries the column.
 *
 * ## The count travels, the people do not
 *
 * ADR-0025 §3, enforced by `NoPersonalDataInAuditContextTest`: scalars only. A
 * row about a list of passport numbers is exactly the row that would be tempted
 * to carry one.
 */
final class ManifestGenerated implements Auditable
{
    use Dispatchable;

    public function __construct(
        private readonly Model $subject,
        private readonly int $onBoard,
        private readonly ?int $userId = null,
    ) {}

    public function auditEntry(): AuditEntryData
    {
        return AuditEntryData::forModel(
            action: AuditAction::ManifestGenerated,
            subject: $this->subject,
            label: $this->label(),
            context: [
                'people' => $this->onBoard,
                // Recorded even though the listener captures the ambient user,
                // because a manifest can also be generated by a job on somebody's
                // behalf and the two must not become indistinguishable.
                'requested_by_user_id' => $this->userId,
                // **No `includes_document_numbers` flag.** The row exists only
                // when they were included, so the flag would say nothing the
                // action does not already say — and `NoPersonalDataInAuditContextTest`
                // is right to refuse a key with that phrase in it, whatever the
                // value beside it happens to be.
            ],
        );
    }

    /**
     * Something a person can find the sailing by, months later.
     */
    private function label(): string
    {
        if ($this->subject instanceof Departure) {
            return $this->subject->local_date->toDateString() . ' ' . $this->subject->local_time;
        }

        return $this->subject instanceof Booking
            ? $this->subject->reference
            : (string) $this->subject->getKey();
    }
}
