-- Kaiki - MySQL 8 schema snapshot (ENV-10).
--
-- Generated by `composer schema:snapshot`, which needs a MySQL 8 connection and so
-- runs in CI rather than on the SQLite local stack. Never edited by hand.
--
-- Not named mysql-schema.sql on purpose: Laravel loads a file at that path instead
-- of running the migrations, which would quietly retire the guarantee this file exists to give.
--
-- migrations-fingerprint: sha256:40654c62b005d64393abe793fa2fe2c0e315689e13e929baac642b1ad1e84a9d

DROP TABLE IF EXISTS `age_bands`;
CREATE TABLE `age_bands` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `uuid` char(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `product_id` bigint unsigned NOT NULL,
  `code` varchar(24) COLLATE utf8mb4_unicode_ci NOT NULL,
  `label` json NOT NULL,
  `min_age` tinyint unsigned NOT NULL DEFAULT '0',
  `max_age` tinyint unsigned DEFAULT NULL,
  `counts_toward_capacity` tinyint(1) NOT NULL DEFAULT '1',
  `pricing_mode` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'multiplier',
  `price_multiplier_bp` smallint unsigned DEFAULT NULL,
  `is_base` tinyint(1) NOT NULL DEFAULT '0',
  `requires_adult` tinyint(1) NOT NULL DEFAULT '0',
  `sort_order` smallint unsigned NOT NULL DEFAULT '0',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `age_bands_tenant_product_code_uq` (`tenant_id`,`product_id`,`code`),
  UNIQUE KEY `age_bands_uuid_unique` (`uuid`),
  KEY `age_bands_product_id_foreign` (`product_id`),
  KEY `age_bands_tenant_product_sort_idx` (`tenant_id`,`product_id`,`sort_order`),
  CONSTRAINT `age_bands_product_id_foreign` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE CASCADE,
  CONSTRAINT `age_bands_tenant_id_foreign` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
DROP TABLE IF EXISTS `api_keys`;
CREATE TABLE `api_keys` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL,
  `name` varchar(80) COLLATE utf8mb4_unicode_ci NOT NULL,
  `type` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL,
  `environment` varchar(8) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'live',
  `prefix` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `secret_hash` char(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `last_four` char(4) COLLATE utf8mb4_unicode_ci NOT NULL,
  `scopes` json NOT NULL,
  `allowed_origins` json NOT NULL,
  `last_used_at` timestamp NULL DEFAULT NULL,
  `expires_at` timestamp NULL DEFAULT NULL,
  `revoked_at` timestamp NULL DEFAULT NULL,
  `created_by_user_id` bigint unsigned DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `api_keys_prefix_unique` (`prefix`),
  UNIQUE KEY `api_keys_secret_hash_unique` (`secret_hash`),
  KEY `api_keys_created_by_user_id_foreign` (`created_by_user_id`),
  KEY `api_keys_tenant_type_idx` (`tenant_id`,`type`,`revoked_at`),
  CONSTRAINT `api_keys_created_by_user_id_foreign` FOREIGN KEY (`created_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `api_keys_tenant_id_foreign` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
DROP TABLE IF EXISTS `brand_profiles`;
CREATE TABLE `brand_profiles` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL,
  `logo_light_path` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `logo_dark_path` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `favicon_path` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `email_header_image_path` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `color_primary` char(7) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '#0F62FE',
  `color_secondary` char(7) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '#0B3D91',
  `color_accent` char(7) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '#FFB000',
  `color_background` char(7) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '#FFFFFF',
  `color_text` char(7) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '#101828',
  `font_family` varchar(80) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'Inter',
  `font_source` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'system',
  `button_radius_px` tinyint unsigned NOT NULL DEFAULT '8',
  `widget_theme` varchar(8) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'auto',
  `email_footer_text` json DEFAULT NULL,
  `social_links` json NOT NULL,
  `custom_css` text COLLATE utf8mb4_unicode_ci,
  `contrast_warnings` json NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `brand_profiles_tenant_id_unique` (`tenant_id`),
  CONSTRAINT `brand_profiles_tenant_id_foreign` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
DROP TABLE IF EXISTS `cache`;
CREATE TABLE `cache` (
  `key` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `value` mediumtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `expiration` int NOT NULL,
  PRIMARY KEY (`key`),
  KEY `cache_expiration_index` (`expiration`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
DROP TABLE IF EXISTS `cache_locks`;
CREATE TABLE `cache_locks` (
  `key` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `owner` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `expiration` int NOT NULL,
  PRIMARY KEY (`key`),
  KEY `cache_locks_expiration_index` (`expiration`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
DROP TABLE IF EXISTS `cancellation_policies`;
CREATE TABLE `cancellation_policies` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL,
  `name` json NOT NULL,
  `summary` json DEFAULT NULL,
  `free_cancellation_hours` smallint unsigned DEFAULT NULL,
  `weather_refund_percent` tinyint unsigned NOT NULL DEFAULT '100',
  `force_majeure_voucher_months` tinyint unsigned NOT NULL DEFAULT '18',
  `no_show_refund_percent` tinyint unsigned NOT NULL DEFAULT '0',
  `is_default` tinyint(1) NOT NULL DEFAULT '0',
  `search_index` text COLLATE utf8mb4_unicode_ci,
  `name_sort_el` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `name_sort_en` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `cxl_policies_tenant_default_idx` (`tenant_id`,`is_default`),
  KEY `cxl_policies_tenant_name_sort_el_idx` (`tenant_id`,`name_sort_el`),
  KEY `cxl_policies_tenant_name_sort_en_idx` (`tenant_id`,`name_sort_en`),
  CONSTRAINT `cancellation_policies_tenant_id_foreign` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
DROP TABLE IF EXISTS `cancellation_policy_tiers`;
CREATE TABLE `cancellation_policy_tiers` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL,
  `cancellation_policy_id` bigint unsigned NOT NULL,
  `days_before` smallint unsigned NOT NULL,
  `refund_percent` tinyint unsigned NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `cxl_tiers_policy_days_uq` (`tenant_id`,`cancellation_policy_id`,`days_before`),
  KEY `cancellation_policy_tiers_cancellation_policy_id_foreign` (`cancellation_policy_id`),
  KEY `cxl_tiers_policy_days_idx` (`tenant_id`,`cancellation_policy_id`,`days_before`),
  CONSTRAINT `cancellation_policy_tiers_cancellation_policy_id_foreign` FOREIGN KEY (`cancellation_policy_id`) REFERENCES `cancellation_policies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `cancellation_policy_tiers_tenant_id_foreign` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
DROP TABLE IF EXISTS `departures`;
CREATE TABLE `departures` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `uuid` char(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `product_id` bigint unsigned NOT NULL,
  `vessel_id` bigint unsigned NOT NULL,
  `schedule_rule_id` bigint unsigned DEFAULT NULL,
  `local_date` date NOT NULL,
  `local_time` time NOT NULL,
  `starts_at_utc` timestamp NOT NULL,
  `ends_at_utc` timestamp NOT NULL,
  `dst_ambiguous` tinyint(1) NOT NULL DEFAULT '0',
  `capacity` smallint unsigned NOT NULL,
  `min_pax` smallint unsigned NOT NULL DEFAULT '0',
  `seats_sold` smallint unsigned NOT NULL DEFAULT '0',
  `seats_held` smallint unsigned NOT NULL DEFAULT '0',
  `status` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'scheduled',
  `cancel_reason` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cancelled_at` timestamp NULL DEFAULT NULL,
  `cancelled_by_user_id` bigint unsigned DEFAULT NULL,
  `cancellation_note` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `is_blocked` tinyint(1) NOT NULL DEFAULT '0',
  `notes` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `completed_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `departures_tenant_prod_start_uq` (`tenant_id`,`product_id`,`starts_at_utc`),
  UNIQUE KEY `departures_uuid_unique` (`uuid`),
  KEY `departures_product_id_foreign` (`product_id`),
  KEY `departures_vessel_id_foreign` (`vessel_id`),
  KEY `departures_schedule_rule_id_foreign` (`schedule_rule_id`),
  KEY `departures_cancelled_by_user_id_foreign` (`cancelled_by_user_id`),
  KEY `departures_avail_idx` (`tenant_id`,`product_id`,`local_date`,`status`),
  KEY `departures_vessel_window_idx` (`tenant_id`,`vessel_id`,`starts_at_utc`,`ends_at_utc`),
  KEY `departures_at_risk_idx` (`tenant_id`,`status`,`starts_at_utc`),
  KEY `departures_tenant_date_idx` (`tenant_id`,`local_date`,`status`),
  KEY `departures_schedule_rule_idx` (`tenant_id`,`schedule_rule_id`),
  CONSTRAINT `departures_cancelled_by_user_id_foreign` FOREIGN KEY (`cancelled_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `departures_product_id_foreign` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `departures_schedule_rule_id_foreign` FOREIGN KEY (`schedule_rule_id`) REFERENCES `schedule_rules` (`id`) ON DELETE SET NULL,
  CONSTRAINT `departures_tenant_id_foreign` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`) ON DELETE CASCADE,
  CONSTRAINT `departures_vessel_id_foreign` FOREIGN KEY (`vessel_id`) REFERENCES `vessels` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
DROP TABLE IF EXISTS `extras`;
CREATE TABLE `extras` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `uuid` char(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `name` json NOT NULL,
  `description` json DEFAULT NULL,
  `pricing_type` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL,
  `price_cents` int unsigned DEFAULT NULL,
  `vat_rate_id` bigint unsigned DEFAULT NULL,
  `max_qty` smallint unsigned DEFAULT NULL,
  `is_tenant_wide` tinyint(1) NOT NULL DEFAULT '0',
  `is_required` tinyint(1) NOT NULL DEFAULT '0',
  `counts_toward_capacity` tinyint(1) NOT NULL DEFAULT '0',
  `prices_all_pax` tinyint(1) NOT NULL DEFAULT '0',
  `image_path` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `sort_order` smallint unsigned NOT NULL DEFAULT '0',
  `search_index` text COLLATE utf8mb4_unicode_ci,
  `name_sort_el` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `name_sort_en` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `extras_uuid_unique` (`uuid`),
  KEY `extras_vat_rate_id_foreign` (`vat_rate_id`),
  KEY `extras_tenant_active_idx` (`tenant_id`,`is_active`,`sort_order`),
  KEY `extras_tenant_wide_idx` (`tenant_id`,`is_tenant_wide`,`is_active`),
  KEY `extras_tenant_name_sort_el_idx` (`tenant_id`,`name_sort_el`),
  KEY `extras_tenant_name_sort_en_idx` (`tenant_id`,`name_sort_en`),
  CONSTRAINT `extras_tenant_id_foreign` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`) ON DELETE CASCADE,
  CONSTRAINT `extras_vat_rate_id_foreign` FOREIGN KEY (`vat_rate_id`) REFERENCES `vat_rates` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
DROP TABLE IF EXISTS `failed_jobs`;
CREATE TABLE `failed_jobs` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `uuid` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `connection` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `queue` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `payload` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `exception` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `failed_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `failed_jobs_uuid_unique` (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
DROP TABLE IF EXISTS `job_batches`;
CREATE TABLE `job_batches` (
  `id` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `total_jobs` int NOT NULL,
  `pending_jobs` int NOT NULL,
  `failed_jobs` int NOT NULL,
  `failed_job_ids` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `options` mediumtext COLLATE utf8mb4_unicode_ci,
  `cancelled_at` int DEFAULT NULL,
  `created_at` int NOT NULL,
  `finished_at` int DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
DROP TABLE IF EXISTS `jobs`;
CREATE TABLE `jobs` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `queue` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `payload` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `attempts` tinyint unsigned NOT NULL,
  `reserved_at` int unsigned DEFAULT NULL,
  `available_at` int unsigned NOT NULL,
  `created_at` int unsigned NOT NULL,
  PRIMARY KEY (`id`),
  KEY `jobs_queue_index` (`queue`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
DROP TABLE IF EXISTS `migrations`;
CREATE TABLE `migrations` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `migration` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `batch` int NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
DROP TABLE IF EXISTS `password_reset_tokens`;
CREATE TABLE `password_reset_tokens` (
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `token` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
DROP TABLE IF EXISTS `ports`;
CREATE TABLE `ports` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `uuid` char(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `name` json NOT NULL,
  `address` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `lat` decimal(10,7) DEFAULT NULL,
  `lng` decimal(10,7) DEFAULT NULL,
  `instructions` json DEFAULT NULL,
  `photo_path` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `maps_url` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `sort_order` smallint unsigned NOT NULL DEFAULT '0',
  `search_index` text COLLATE utf8mb4_unicode_ci,
  `name_sort_el` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `name_sort_en` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ports_uuid_unique` (`uuid`),
  KEY `ports_tenant_active_idx` (`tenant_id`,`is_active`,`sort_order`),
  KEY `ports_tenant_name_sort_el_idx` (`tenant_id`,`name_sort_el`),
  KEY `ports_tenant_name_sort_en_idx` (`tenant_id`,`name_sort_en`),
  CONSTRAINT `ports_tenant_id_foreign` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
DROP TABLE IF EXISTS `product_extra`;
CREATE TABLE `product_extra` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL,
  `product_id` bigint unsigned NOT NULL,
  `extra_id` bigint unsigned NOT NULL,
  `price_cents_override` int unsigned DEFAULT NULL,
  `max_qty_override` smallint unsigned DEFAULT NULL,
  `is_required_override` tinyint(1) DEFAULT NULL,
  `sort_order` smallint unsigned NOT NULL DEFAULT '0',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `product_extra_uq` (`tenant_id`,`product_id`,`extra_id`),
  KEY `product_extra_product_id_foreign` (`product_id`),
  KEY `product_extra_extra_id_foreign` (`extra_id`),
  KEY `product_extra_tenant_product_idx` (`tenant_id`,`product_id`,`sort_order`),
  CONSTRAINT `product_extra_extra_id_foreign` FOREIGN KEY (`extra_id`) REFERENCES `extras` (`id`) ON DELETE CASCADE,
  CONSTRAINT `product_extra_product_id_foreign` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE CASCADE,
  CONSTRAINT `product_extra_tenant_id_foreign` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
DROP TABLE IF EXISTS `products`;
CREATE TABLE `products` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `uuid` char(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `vessel_id` bigint unsigned DEFAULT NULL,
  `slug` varchar(120) COLLATE utf8mb4_unicode_ci NOT NULL,
  `category` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `mode` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL,
  `title` json NOT NULL,
  `summary` json DEFAULT NULL,
  `description` json DEFAULT NULL,
  `duration_minutes` smallint unsigned NOT NULL,
  `default_start_time` time DEFAULT NULL,
  `flexible_start` tinyint(1) NOT NULL DEFAULT '0',
  `earliest_start_time` time DEFAULT NULL,
  `latest_start_time` time DEFAULT NULL,
  `check_in_offset_minutes` smallint unsigned NOT NULL DEFAULT '30',
  `meeting_point_id` bigint unsigned DEFAULT NULL,
  `includes` json DEFAULT NULL,
  `excludes` json DEFAULT NULL,
  `what_to_bring` json DEFAULT NULL,
  `itinerary_stops` json DEFAULT NULL,
  `route_map_image_path` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `images` json NOT NULL,
  `min_pax` smallint unsigned NOT NULL DEFAULT '0',
  `max_pax` smallint unsigned NOT NULL,
  `min_booking_pax` smallint unsigned NOT NULL DEFAULT '1',
  `cancellation_policy_id` bigint unsigned DEFAULT NULL,
  `guest_details_required` tinyint(1) NOT NULL DEFAULT '0',
  `guest_details_deadline_hours` smallint unsigned NOT NULL DEFAULT '48',
  `vat_rate_id` bigint unsigned DEFAULT NULL,
  `mydata_income_class` varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `price_from_cents` int unsigned DEFAULT NULL,
  `status` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'draft',
  `sort_order` smallint unsigned NOT NULL DEFAULT '0',
  `meta_title` json DEFAULT NULL,
  `meta_description` json DEFAULT NULL,
  `og_image_path` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `is_featured` tinyint(1) NOT NULL DEFAULT '0',
  `search_index` text COLLATE utf8mb4_unicode_ci,
  `title_sort_el` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `title_sort_en` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `products_tenant_slug_unique` (`tenant_id`,`slug`),
  UNIQUE KEY `products_uuid_unique` (`uuid`),
  KEY `products_vessel_id_foreign` (`vessel_id`),
  KEY `products_meeting_point_id_foreign` (`meeting_point_id`),
  KEY `products_cancellation_policy_id_foreign` (`cancellation_policy_id`),
  KEY `products_vat_rate_id_foreign` (`vat_rate_id`),
  KEY `products_tenant_status_sort_idx` (`tenant_id`,`status`,`sort_order`),
  KEY `products_tenant_vessel_idx` (`tenant_id`,`vessel_id`),
  KEY `products_tenant_cat_status_idx` (`tenant_id`,`category`,`status`),
  KEY `products_tenant_mode_idx` (`tenant_id`,`mode`),
  KEY `products_tenant_title_sort_el_idx` (`tenant_id`,`title_sort_el`),
  KEY `products_tenant_title_sort_en_idx` (`tenant_id`,`title_sort_en`),
  CONSTRAINT `products_cancellation_policy_id_foreign` FOREIGN KEY (`cancellation_policy_id`) REFERENCES `cancellation_policies` (`id`) ON DELETE SET NULL,
  CONSTRAINT `products_meeting_point_id_foreign` FOREIGN KEY (`meeting_point_id`) REFERENCES `ports` (`id`) ON DELETE SET NULL,
  CONSTRAINT `products_tenant_id_foreign` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`) ON DELETE CASCADE,
  CONSTRAINT `products_vat_rate_id_foreign` FOREIGN KEY (`vat_rate_id`) REFERENCES `vat_rates` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `products_vessel_id_foreign` FOREIGN KEY (`vessel_id`) REFERENCES `vessels` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
DROP TABLE IF EXISTS `rate_plan_prices`;
CREATE TABLE `rate_plan_prices` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL,
  `rate_plan_id` bigint unsigned NOT NULL,
  `age_band_id` bigint unsigned NOT NULL,
  `price_cents` int unsigned NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `rate_plan_prices_plan_band_uq` (`tenant_id`,`rate_plan_id`,`age_band_id`),
  KEY `rate_plan_prices_rate_plan_id_foreign` (`rate_plan_id`),
  KEY `rate_plan_prices_age_band_id_foreign` (`age_band_id`),
  KEY `rate_plan_prices_tenant_plan_idx` (`tenant_id`,`rate_plan_id`),
  CONSTRAINT `rate_plan_prices_age_band_id_foreign` FOREIGN KEY (`age_band_id`) REFERENCES `age_bands` (`id`) ON DELETE CASCADE,
  CONSTRAINT `rate_plan_prices_rate_plan_id_foreign` FOREIGN KEY (`rate_plan_id`) REFERENCES `rate_plans` (`id`) ON DELETE CASCADE,
  CONSTRAINT `rate_plan_prices_tenant_id_foreign` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
DROP TABLE IF EXISTS `rate_plans`;
CREATE TABLE `rate_plans` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL,
  `product_id` bigint unsigned NOT NULL,
  `season_id` bigint unsigned DEFAULT NULL,
  `name` varchar(80) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `vessel_price_cents` int unsigned DEFAULT NULL,
  `extra_hour_price_cents` int unsigned DEFAULT NULL,
  `deposit_type` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'none',
  `deposit_percent` tinyint unsigned DEFAULT NULL,
  `deposit_fixed_cents` int unsigned DEFAULT NULL,
  `min_lead_time_hours` smallint unsigned NOT NULL DEFAULT '0',
  `max_advance_days` smallint unsigned DEFAULT NULL,
  `min_pax_override` smallint unsigned DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `rate_plans_tenant_prod_season_uq` (`tenant_id`,`product_id`,`season_id`),
  KEY `rate_plans_product_id_foreign` (`product_id`),
  KEY `rate_plans_season_id_foreign` (`season_id`),
  KEY `rate_plans_tenant_product_idx` (`tenant_id`,`product_id`,`is_active`),
  CONSTRAINT `rate_plans_product_id_foreign` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE CASCADE,
  CONSTRAINT `rate_plans_season_id_foreign` FOREIGN KEY (`season_id`) REFERENCES `seasons` (`id`) ON DELETE CASCADE,
  CONSTRAINT `rate_plans_tenant_id_foreign` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
DROP TABLE IF EXISTS `role_assignments`;
CREATE TABLE `role_assignments` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL,
  `user_id` bigint unsigned NOT NULL,
  `role` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `granted_by_user_id` bigint unsigned DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `role_assign_tenant_user_role_uq` (`tenant_id`,`user_id`,`role`),
  KEY `role_assignments_user_id_foreign` (`user_id`),
  KEY `role_assignments_granted_by_user_id_foreign` (`granted_by_user_id`),
  KEY `role_assign_tenant_role_idx` (`tenant_id`,`role`),
  CONSTRAINT `role_assignments_granted_by_user_id_foreign` FOREIGN KEY (`granted_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `role_assignments_tenant_id_foreign` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`) ON DELETE CASCADE,
  CONSTRAINT `role_assignments_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
DROP TABLE IF EXISTS `schedule_rules`;
CREATE TABLE `schedule_rules` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL,
  `product_id` bigint unsigned NOT NULL,
  `vessel_id` bigint unsigned DEFAULT NULL,
  `weekday_mask` tinyint unsigned NOT NULL,
  `start_time` time NOT NULL,
  `valid_from` date NOT NULL,
  `valid_until` date DEFAULT NULL,
  `capacity_override` smallint unsigned DEFAULT NULL,
  `generate_days_ahead` smallint unsigned NOT NULL DEFAULT '180',
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `last_generated_on` date DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `schedule_rules_product_id_foreign` (`product_id`),
  KEY `schedule_rules_vessel_id_foreign` (`vessel_id`),
  KEY `schedule_rules_tenant_active_idx` (`tenant_id`,`is_active`,`valid_from`),
  KEY `schedule_rules_tenant_product_idx` (`tenant_id`,`product_id`),
  CONSTRAINT `schedule_rules_product_id_foreign` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE CASCADE,
  CONSTRAINT `schedule_rules_tenant_id_foreign` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`) ON DELETE CASCADE,
  CONSTRAINT `schedule_rules_vessel_id_foreign` FOREIGN KEY (`vessel_id`) REFERENCES `vessels` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
DROP TABLE IF EXISTS `season_date_ranges`;
CREATE TABLE `season_date_ranges` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL,
  `season_id` bigint unsigned NOT NULL,
  `starts_on` date NOT NULL,
  `ends_on` date NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `season_date_ranges_season_id_foreign` (`season_id`),
  KEY `season_ranges_tenant_dates_idx` (`tenant_id`,`starts_on`,`ends_on`),
  KEY `season_ranges_season_idx` (`tenant_id`,`season_id`),
  CONSTRAINT `season_date_ranges_season_id_foreign` FOREIGN KEY (`season_id`) REFERENCES `seasons` (`id`) ON DELETE CASCADE,
  CONSTRAINT `season_date_ranges_tenant_id_foreign` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
DROP TABLE IF EXISTS `seasons`;
CREATE TABLE `seasons` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL,
  `name` json NOT NULL,
  `code` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `priority` smallint unsigned NOT NULL DEFAULT '0',
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `search_index` text COLLATE utf8mb4_unicode_ci,
  `name_sort_el` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `name_sort_en` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `seasons_tenant_code_uq` (`tenant_id`,`code`),
  KEY `seasons_tenant_priority_idx` (`tenant_id`,`priority`,`is_active`),
  KEY `seasons_tenant_name_sort_el_idx` (`tenant_id`,`name_sort_el`),
  KEY `seasons_tenant_name_sort_en_idx` (`tenant_id`,`name_sort_en`),
  CONSTRAINT `seasons_tenant_id_foreign` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
DROP TABLE IF EXISTS `sessions`;
CREATE TABLE `sessions` (
  `id` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `user_id` bigint unsigned DEFAULT NULL,
  `ip_address` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `user_agent` text COLLATE utf8mb4_unicode_ci,
  `payload` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `last_activity` int NOT NULL,
  PRIMARY KEY (`id`),
  KEY `sessions_user_id_index` (`user_id`),
  KEY `sessions_last_activity_index` (`last_activity`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
DROP TABLE IF EXISTS `tenant_domains`;
CREATE TABLE `tenant_domains` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL,
  `hostname` varchar(190) COLLATE utf8mb4_unicode_ci NOT NULL,
  `status` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'pending',
  `verification_token` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `verified_at` timestamp NULL DEFAULT NULL,
  `last_checked_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `tenant_domains_hostname_unique` (`hostname`),
  KEY `tenant_domains_status_hostname_idx` (`status`,`hostname`),
  KEY `tenant_domains_tenant_status_idx` (`tenant_id`,`status`),
  CONSTRAINT `tenant_domains_tenant_id_foreign` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
DROP TABLE IF EXISTS `tenants`;
CREATE TABLE `tenants` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `uuid` char(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` varchar(120) COLLATE utf8mb4_unicode_ci NOT NULL,
  `slug` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `legal_name` varchar(180) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `vat_number` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tax_office` varchar(60) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `gemi_number` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `address_line1` varchar(180) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `address_line2` varchar(180) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `city` varchar(80) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `postcode` varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `country` char(2) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'GR',
  `phone` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `email` varchar(190) COLLATE utf8mb4_unicode_ci NOT NULL,
  `timezone` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'Europe/Athens',
  `default_locale` char(2) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'el',
  `supported_locales` json NOT NULL,
  `currency` char(3) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'EUR',
  `plan` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'trial',
  `status` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'trialing',
  `trial_ends_at` timestamp NULL DEFAULT NULL,
  `custom_domain` varchar(190) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `custom_domain_verified_at` timestamp NULL DEFAULT NULL,
  `hosted_page_enabled` tinyint(1) NOT NULL DEFAULT '1',
  `is_sandbox` tinyint(1) NOT NULL DEFAULT '0',
  `turnaround_buffer_minutes` smallint unsigned NOT NULL DEFAULT '60',
  `guest_document_retention_days` smallint unsigned NOT NULL DEFAULT '90',
  `auto_issue_invoice` tinyint(1) NOT NULL DEFAULT '0',
  `settings` json NOT NULL,
  `stripe_id` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pm_type` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pm_last_four` char(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `tenants_uuid_unique` (`uuid`),
  UNIQUE KEY `tenants_slug_unique` (`slug`),
  UNIQUE KEY `tenants_custom_domain_unique` (`custom_domain`),
  KEY `tenants_status_index` (`status`),
  KEY `tenants_vat_number_index` (`vat_number`),
  KEY `tenants_stripe_id_index` (`stripe_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `uuid` char(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `tenant_id` bigint unsigned DEFAULT NULL,
  `name` varchar(120) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(190) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email_verified_at` timestamp NULL DEFAULT NULL,
  `password` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `phone` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `locale` char(2) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `is_super_admin` tinyint(1) NOT NULL DEFAULT '0',
  `last_login_at` timestamp NULL DEFAULT NULL,
  `two_factor_secret` text COLLATE utf8mb4_unicode_ci,
  `two_factor_recovery_codes` text COLLATE utf8mb4_unicode_ci,
  `two_factor_confirmed_at` timestamp NULL DEFAULT NULL,
  `remember_token` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `users_uuid_unique` (`uuid`),
  UNIQUE KEY `users_email_unique` (`email`),
  KEY `users_tenant_role_idx` (`tenant_id`,`is_super_admin`),
  CONSTRAINT `users_tenant_id_foreign` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
DROP TABLE IF EXISTS `vat_rates`;
CREATE TABLE `vat_rates` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `code` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `rate_bp` smallint unsigned NOT NULL,
  `vat_category` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` json NOT NULL,
  `valid_from` date NOT NULL,
  `valid_to` date DEFAULT NULL,
  `is_selectable` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `vat_rates_code_from_unique` (`code`,`valid_from`),
  KEY `vat_rates_validity_idx` (`valid_from`,`valid_to`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
DROP TABLE IF EXISTS `vessels`;
CREATE TABLE `vessels` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `uuid` char(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `name` varchar(120) COLLATE utf8mb4_unicode_ci NOT NULL,
  `type` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `registration_number` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `length_cm` smallint unsigned DEFAULT NULL,
  `capacity_max` smallint unsigned NOT NULL,
  `crew_count` tinyint unsigned NOT NULL DEFAULT '1',
  `captain_name` varchar(120) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `home_port_id` bigint unsigned DEFAULT NULL,
  `turnaround_buffer_minutes` smallint unsigned DEFAULT NULL,
  `description` json DEFAULT NULL,
  `specs` json NOT NULL,
  `images` json NOT NULL,
  `status` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'active',
  `sort_order` smallint unsigned NOT NULL DEFAULT '0',
  `search_index` text COLLATE utf8mb4_unicode_ci,
  `name_sort` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `vessels_tenant_name_unique` (`tenant_id`,`name`),
  UNIQUE KEY `vessels_uuid_unique` (`uuid`),
  KEY `vessels_home_port_id_foreign` (`home_port_id`),
  KEY `vessels_tenant_status_idx` (`tenant_id`,`status`,`sort_order`),
  KEY `vessels_tenant_home_port_idx` (`tenant_id`,`home_port_id`),
  KEY `vessels_tenant_name_sort_idx` (`tenant_id`,`name_sort`),
  CONSTRAINT `vessels_home_port_id_foreign` FOREIGN KEY (`home_port_id`) REFERENCES `ports` (`id`) ON DELETE SET NULL,
  CONSTRAINT `vessels_tenant_id_foreign` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES (1,'0001_01_01_000000_create_users_table',1);
INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES (2,'0001_01_01_000001_create_cache_table',1);
INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES (3,'0001_01_01_000002_create_jobs_table',1);
INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES (4,'0001_01_01_000003_create_role_assignments_table',1);
INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES (5,'0001_01_01_000004_create_api_keys_table',1);
INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES (6,'0001_01_01_000005_create_tenant_domains_table',1);
INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES (7,'2026_09_02_000009_create_vat_rates_table',1);
INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES (8,'2026_09_02_000010_create_brand_profiles_table',1);
INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES (9,'2026_09_02_000011_create_ports_table',1);
INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES (10,'2026_09_02_000012_create_vessels_table',1);
INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES (11,'2026_09_02_000013_create_cancellation_policies_table',1);
INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES (12,'2026_09_02_000014_create_cancellation_policy_tiers_table',1);
INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES (13,'2026_09_02_000015_create_products_table',1);
INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES (14,'2026_09_02_000016_create_age_bands_table',1);
INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES (15,'2026_09_02_000017_create_seasons_table',1);
INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES (16,'2026_09_02_000018_create_season_date_ranges_table',1);
INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES (17,'2026_09_02_000019_create_rate_plans_table',1);
INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES (18,'2026_09_02_000020_create_rate_plan_prices_table',1);
INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES (19,'2026_09_02_000021_create_extras_table',1);
INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES (20,'2026_09_02_000022_create_product_extra_table',1);
INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES (21,'2026_09_02_000023_create_schedule_rules_table',1);
INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES (22,'2026_09_02_000024_create_departures_table',1);
